pipeline: Pipeline\CreateRecord
stages:
  id:
    pipeline: Stage\Extract
    args:
      extraction: currentCategory::getEntityId()
      transformations: Prepend("categoryid_")
  type:
    pipeline: Stage\StaticValue
    args:
      value: "KLEVU_CATEGORY"
  attributes:
    pipeline: Pipeline\CreateRecord
    stages:
      name:
        import: Klevu_IndexingCategories::etc/pipeline/category/attributes/name.yml
      description:
        import: Klevu_IndexingCategories::etc/pipeline/category/attributes/description.yml
      url:
        import: Klevu_IndexingCategories::etc/pipeline/category/attributes/url.yml
      visibility:
        import: Klevu_IndexingCategories::etc/pipeline/category/attributes/visibility.yml
      categoryPath:
        import: Klevu_IndexingCategories::etc/pipeline/category/attributes/category_path.yml
      image:
        import: Klevu_IndexingCategories::etc/pipeline/category/attributes/image.yml
